from urllib.parse import urlsplit

from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.db import models

__all__ = [
    "CPE23Item",
    "CPEChangeDescription",
    "CPECheck",
    "CPEDeprecatedBy",
    "CPEDeprecation",
    "CPEDictionary",
    "CPEEvidenceReference",
    "CPEGenerator",
    "CPEItem",
    "CPENote",
    "CPEOrganization",
    "CPEProvenanceOrganizationParticipant",
    "CPEProvenanceRecord",
    "CPEReference",
    "CPETitle",
    "CPEWellFormedName",
    "ExpandedURLValidator",
]

from application.utilities.utils import ANY, cpe23_formatted_string_to_wfn


class ExpandedURLValidator(URLValidator):
    schemes = ["file", "ftp", "ftps", "http", "https", "s3", "ssh", "urn", "ws", "wss"]

    def __call__(self, value):
        if not isinstance(value, str) or len(value) > self.max_length:
            raise ValidationError(self.message, code=self.code, params={"value": value})
        if self.unsafe_chars.intersection(value):
            raise ValidationError(self.message, code=self.code, params={"value": value})
        # Check if the scheme is valid.
        scheme = value.split("://")[0].lower()
        if scheme not in self.schemes:
            raise ValidationError(self.message, code=self.code, params={"value": value})

        # Then check full URL
        try:
            urlsplit(value)
        except ValueError as e:
            raise ValidationError(
                self.message, code=self.code, params={"value": value}
            ) from e

    @property
    def message(self):
        return f"Enter a valid URL. Valid schemes: {', '.join(self.schemes)}"


class CPEDictionary(models.Model):
    """
    Represents a CPE Dictionary.

    Corresponds conceptually to: <cpe_dict:cpe-list>
    NIST IR 7697, Section 5.1.
    """

    # Optional bookkeeping useful for imported dictionaries.
    source_uri = models.CharField(blank=True, validators=[ExpandedURLValidator()])
    imported_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "CPE Dictionary <cpe_dict:cpe-list>"
        verbose_name_plural = "CPE Dictionaries [<cpe_dict:cpe-list>]"

    def __str__(self):
        return f"Dictionary {self.id} {self.source_uri}"


class CPEGenerator(models.Model):
    """
    Corresponds to: <cpe_dict:generator>

    NIST IR 7697 Section 5.2 defines:
      - product_name
      - product_version
      - schema_version
      - timestamp
    """

    dictionary = models.OneToOneField(
        CPEDictionary,
        on_delete=models.CASCADE,
        related_name="generator",
    )

    product_name = models.CharField(
        max_length=255,
        null=True,
    )

    product_version = models.CharField(
        max_length=255,
        null=True,
    )

    schema_version = models.CharField(
        max_length=255,
        default="2.3",
    )

    timestamp = models.DateTimeField(auto_created=True)

    class Meta:
        verbose_name = "CPE Generator <cpe_dict:generator>"
        verbose_name_plural = "CPE Generators [<cpe_dict:generator>]"

    def __str__(self):
        if self.product_name:
            return f"{self.product_name} {self.product_version}".strip()

        return f"Generated by {self.product_name} version {self.product_version} for cpe schema {self.schema_version}"


class CPEItem(models.Model):
    """
    The primary CPE dictionary entry.

    Corresponds to: <cpe_dict:cpe-item>

    NIST IR 7697 Section 5.3.

    The dictionary maintains both the legacy CPE 2.2 URI binding and
    the CPE 2.3 formatted-string binding.
    """

    dictionary = models.ForeignKey(
        CPEDictionary, on_delete=models.CASCADE, related_name="items"
    )

    # CPE 2.2 URI binding.
    name = models.CharField(max_length=2048, help_text="CPE 2.2 URI binding.")

    deprecated = models.BooleanField(
        default=False, help_text="Whether or not the name has been deprecated."
    )

    # Legacy 2.2 deprecation information.
    deprecated_by_cpe22 = models.CharField(
        max_length=2048,
        null=True,
        help_text="Legacy CPE 2.2 name that deprecated this entry.",
    )

    deprecation_date = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    cpe_name_id = models.UUIDField(
        blank=True,
        help_text="Unique CPE identifier. A new field added by NVD.",
        primary_key=True,
    )

    class Meta:
        verbose_name = "CPE Item <cpe_dict:cpe-item>"
        verbose_name_plural = "CPE Items [<cpe_dict:cpe-item>]"
        indexes = [
            models.Index(fields=["name"]),
            models.Index(fields=["deprecated"]),
        ]
        ordering = ["-created_at"]

    def __str__(self):
        return self.cpe23.name


class CPE23Item(models.Model):
    """
    CPE 2.3-specific portion of a CPE dictionary item.

    Corresponds to: <cpe_dict_ext:cpe23-item>

    NIST IR 7697 Section 5.4.

    The `name` is the CPE 2.3 formatted-string binding.
    """

    item = models.OneToOneField(
        CPEItem,
        on_delete=models.CASCADE,
        related_name="cpe23",
    )

    name = models.CharField(
        max_length=4096,
        unique=True,
        help_text="CPE 2.3 formatted-string binding.",
    )

    class Meta:
        verbose_name = "CPE 2.3 Item <cpe_dict_ext:cpe23-item>"
        verbose_name_plural = "CPE 2.3 Items [<cpe_dict_ext:cpe23-item>]"

    def __str__(self):
        return self.name


class CPEWellFormedName(models.Model):
    """
    A well-formed CPE name (WFN) that identifies a single product class

    A WFN has eleven attributes:

        part
        vendor
        product
        version
        update
        edition
        language
        sw_edition
        target_sw
        target_hw
        other

    This model stores the parsed representation in addition to the
    canonical CPE 2.3 formatted string stored by CPE23Item.
    """

    PART_APPLICATION = "a"
    PART_OPERATING_SYSTEM = "o"
    PART_HARDWARE = "h"

    PART_CHOICES = (
        (PART_APPLICATION, "Application"),
        (PART_OPERATING_SYSTEM, "Operating System"),
        (PART_HARDWARE, "Hardware"),
    )

    cpe23_item = models.OneToOneField(
        CPE23Item,
        on_delete=models.CASCADE,
        related_name="wfn",
    )

    part = models.CharField(max_length=1, choices=PART_CHOICES)
    vendor = models.CharField(max_length=255)
    product = models.CharField(max_length=255)
    version = models.CharField(max_length=255)
    update = models.CharField(max_length=255, blank=True)
    edition = models.CharField(max_length=255, blank=True)
    language = models.CharField(max_length=255, blank=True)
    sw_edition = models.CharField(max_length=255, blank=True)
    target_sw = models.CharField(max_length=255, blank=True)
    target_hw = models.CharField(max_length=255, blank=True)
    other = models.CharField(max_length=255, blank=True)

    class Meta:
        verbose_name = "CPE WFN"
        verbose_name_plural = "CPE WFNs"

        indexes = [
            models.Index(fields=["part"]),
            models.Index(fields=["vendor"]),
            models.Index(fields=["product"]),
            models.Index(fields=["version"]),
            models.Index(fields=["vendor", "product"]),
            models.Index(
                fields=[
                    "part",
                    "vendor",
                    "product",
                    "version",
                ]
            ),
        ]

    def __str__(self):
        return ":".join(
            [
                self.part,
                self.vendor,
                self.product,
                self.version,
                self.update,
                self.edition,
                self.language,
                self.sw_edition,
                self.target_sw,
                self.target_hw,
                self.other,
            ]
        )

    def clean(self):
        """
        Basic CPE Dictionary 2.3 acceptance rules.

        NIST IR 7697 Section 6.1 requires known data for:
            part
            vendor
            product
            version

        ANY is not permitted for these four fields.
        """

        required = {
            "part": self.part,
            "vendor": self.vendor,
            "product": self.product,
            "version": self.version,
        }

        for field, value in required.items():
            if not value:
                raise ValidationError(
                    {field: "This CPE attribute must contain known data."}
                )

            if value == ANY:
                raise ValidationError(
                    {field: "ANY is not permitted for identifier names."}
                )

        if ANY in self.vendor or "?" in self.vendor:
            raise ValidationError({"vendor": "Wildcard characters are not allowed."})

        if ANY in self.product or "?" in self.product:
            raise ValidationError({"product": "Wildcard characters are not allowed."})

    @classmethod
    def create_from_cpe23_model(cls, cpe23_item: CPE23Item):
        (
            part,
            vendor,
            product,
            version,
            update,
            edition,
            language,
            sw_edition,
            target_sw,
            target_hw,
            other,
        ) = cpe23_formatted_string_to_wfn(cpe23_item.name)
        cls.objects.create(
            cpe23_item=cpe23_item,
            part=part,
            vendor=vendor,
            product=product,
            version=version,
            update=update,
            edition=edition,
            language=language,
            sw_edition=sw_edition,
            target_sw=target_sw,
            target_hw=target_hw,
            other=other,
        )


class CPETitle(models.Model):
    """
    Corresponds to: <cpe_dict:title>

    A CPE item may have one title per language.
    """

    item = models.ForeignKey(
        CPEItem,
        on_delete=models.CASCADE,
        related_name="titles",
        help_text="The UUID of the CPE item",
    )

    language = models.CharField(max_length=16, default="en-US", help_text="xml:lang")
    value = models.CharField(max_length=2048, help_text="The title text")

    class Meta:
        verbose_name = "CPE Title <cpe_dict:title>"
        verbose_name_plural = "CPE Titles [<cpe_dict:title>]"

        constraints = [
            models.UniqueConstraint(
                fields=["item", "language"],
                name="unique_cpe_title_language",
            ),
        ]

        indexes = [
            models.Index(fields=["language"]),
        ]

    def __str__(self):
        return self.value


class CPENote(models.Model):
    """
    Corresponds to: <cpe_dict:notes>

    NIST permits notes in multiple languages.
    """

    item = models.ForeignKey(
        CPEItem,
        on_delete=models.CASCADE,
        related_name="notes",
    )

    language = models.CharField(
        max_length=16,
        default="en-US",
        help_text="xml:lang",
    )

    value = models.TextField()

    class Meta:
        verbose_name = "CPE Note <cpe_dict:notes>"
        verbose_name_plural = "CPE Notes <cpe_dict:notes>"

        constraints = [
            models.UniqueConstraint(
                fields=["item", "language"],
                name="unique_cpe_note_language",
            ),
        ]

    def __str__(self):
        return self.value[:100]


class CPEReference(models.Model):
    """
    External reference associated with a CPE item.

    Corresponds to: <cpe_dict:references>
    """

    item = models.ForeignKey(
        CPEItem, on_delete=models.CASCADE, related_name="references"
    )

    description = models.TextField(blank=True)
    href = models.CharField(max_length=4096, validators=[ExpandedURLValidator()])

    class Meta:
        verbose_name = "CPE Reference <cpe_dict:references>"
        verbose_name_plural = "CPE References [<cpe_dict:references>]"

    def __str__(self):
        return self.href


class CPECheck(models.Model):
    """
    A check identifies an external specification/system and
    an identifier that can be used to verify whether a platform
    matches the CPE.

    Corresponds to: <cpe_dict:check>

    Example:
        OVAL definition
    """

    item = models.ForeignKey(
        CPEItem,
        on_delete=models.CASCADE,
        related_name="checks",
    )

    check_id = models.CharField(
        max_length=1024,
        help_text="Identifier within the checking system.",
    )

    file = models.CharField(
        max_length=4096,
        help_text="An OPTIONAL external file reference (for example, a pointer to the file where the check is defined).",
        validators=[ExpandedURLValidator()],
        null=True,
    )

    system = models.CharField(
        max_length=4096,
        help_text="URI identifying the checking system/specification.",
        validators=[],
    )

    class Meta:
        verbose_name = "CPE Check <cpe_dict:check>"
        verbose_name_plural = "CPE Checks [<cpe_dict:check>]"

        indexes = [
            models.Index(fields=["check_id"]),
        ]

    def __str__(self):
        return self.check_id


class CPEProvenanceRecord(models.Model):
    """
    Corresponds to: <cpe_dict_ext:provenance-record>

    NIST IR 7697 Section 5.5.
    """

    cpe23_item = models.OneToOneField(
        CPE23Item,
        on_delete=models.CASCADE,
        related_name="provenance",
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        verbose_name = "CPE Provenance Record <cpe_dict_ext:provenance-record>"
        verbose_name_plural = (
            "CPE Provenance Records [<cpe_dict_ext:provenance-record>]"
        )

    def __str__(self):
        return f"ProvenanceRecord of {self.cpe23_item.name}"


class CPEOrganization(models.Model):
    """
    Organizations that can participate in CPE provenance.

    Corresponds to: Part of <cpe_dict_ext:provenance-record>
    """

    description = models.CharField(
        max_length=2048,
        null=True,
        help_text="A high-level description of the organization acting as a CPE Provenance submitter or authority.",
    )

    name = models.CharField(
        max_length=512, help_text="Human readable name of the organization."
    )

    system_id = models.CharField(
        max_length=4096,
        help_text="Unique URI representing the organization.",
        unique=True,
        validators=[ExpandedURLValidator()],
    )

    class Meta:
        verbose_name = "CPE Organization"
        verbose_name_plural = "CPE Organizations"

        indexes = [
            models.Index(fields=["system_id"]),
        ]

    def __str__(self):
        return f"{self.name} {self.system_id}"


class CPEProvenanceOrganizationParticipant(models.Model):
    """
    Organization participating in CPE provenance.

    This can represent either:
        - <cpe_dict_ext:submitter>
        - <cpe_dict_ext:authority>
    """

    provenance = models.ForeignKey(
        CPEProvenanceRecord,
        on_delete=models.CASCADE,
        related_name="organizations",
    )

    ROLE_SUBMITTER = "submitter"
    ROLE_AUTHORITY = "authority"

    ROLE_CHOICES = (
        (ROLE_SUBMITTER, "Submitter"),
        (ROLE_AUTHORITY, "Authority"),
    )

    date = models.DateTimeField(
        help_text="Date the organization performed the action.",
    )

    role = models.CharField(
        max_length=16,
        choices=ROLE_CHOICES,
    )

    system_id = models.ForeignKey(
        CPEOrganization,
        on_delete=models.CASCADE,
        related_name="organization",
    )

    class Meta:
        verbose_name = "CPE Organization Participant <cpe_dict_ext:authority|submitter>"
        verbose_name_plural = (
            "CPE Organization Participants [<cpe_dict_ext:authority|submitter>]"
        )

    def __str__(self):
        return f"{self.role}: {self.system_id.name}"


class CPEChangeDescription(models.Model):
    """
    Corresponds to: <cpe_dict_ext:change-description>

    NIST IR 7697 defines the following change types:

        ORIGINAL_RECORD
        AUTHORITY_CHANGE
        DEPRECATION
        DEPRECATION_MODIFICATION
    """

    ORIGINAL_RECORD = "ORIGINAL_RECORD"
    AUTHORITY_CHANGE = "AUTHORITY_CHANGE"
    DEPRECATION = "DEPRECATION"
    DEPRECATION_MODIFICATION = "DEPRECATION_MODIFICATION"

    CHANGE_TYPE_CHOICES = (
        (ORIGINAL_RECORD, "Original Record"),
        (AUTHORITY_CHANGE, "Authority Change"),
        (DEPRECATION, "Deprecation"),
        (
            DEPRECATION_MODIFICATION,
            "Deprecation Modification",
        ),
    )

    provenance = models.ForeignKey(
        CPEProvenanceRecord,
        on_delete=models.CASCADE,
        related_name="changes",
    )

    date = models.DateTimeField(
        null=True,
    )

    change_type = models.CharField(
        max_length=32,
        choices=CHANGE_TYPE_CHOICES,
    )

    comments = models.TextField(
        null=True,
    )

    class Meta:
        verbose_name = "CPE Change Description <cpe_dict_ext:change-description>"
        verbose_name_plural = (
            "CPE Change Descriptions [<cpe_dict_ext:change-description>]"
        )

    def __str__(self):
        return f"Change for {self.provenance}"


class CPEEvidenceReference(models.Model):
    """
    Evidence supporting a provenance change.

    Corresponds to: <cpe_dict_ext:evidence-reference>
    """

    CURATOR_UPDATE = "CURATOR_UPDATE"
    VENDOR_FIX = "VENDOR_FIX"
    THIRD_PARTY_FIX = "THIRD_PARTY_FIX"

    EVIDENCE_CHOICES = (
        (CURATOR_UPDATE, "Curator Update"),
        (VENDOR_FIX, "Vendor Fix"),
        (THIRD_PARTY_FIX, "Third Party Fix"),
    )

    change = models.OneToOneField(
        CPEChangeDescription,
        on_delete=models.CASCADE,
        related_name="evidence",
    )

    evidence = models.CharField(
        max_length=32,
        choices=EVIDENCE_CHOICES,
    )

    href = models.CharField(
        max_length=4096,
        validators=[ExpandedURLValidator()],
    )

    class Meta:
        verbose_name = "CPE Evidence Reference <cpe_dict_ext:evidence-reference>"
        verbose_name_plural = (
            "CPE Evidence References [<cpe_dict_ext:evidence-reference>]"
        )

    def __str__(self):
        return f"Evidence Reference for {self.change}"


class CPEDeprecation(models.Model):
    """
    A single deprecation event.

    IMPORTANT:
    CPE 2.3 allows multiple deprecation records for the same
    CPE identifier. Therefore, this is NOT a OneToOneField.

    Corresponds to: <cpe_dict_ext:deprecation>

    NIST IR 7697 Section 5.6.
    """

    cpe23_item = models.ForeignKey(
        CPE23Item,
        on_delete=models.CASCADE,
        related_name="deprecations",
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    date = models.DateTimeField(
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = "CPE Deprecation <cpe_dict_ext:deprecation>"
        verbose_name_plural = "CPE Deprecations [<cpe_dict_ext:deprecation>]"

    def __str__(self):
        return f"Deprecates {self.cpe23_item.name}"


class CPEDeprecatedBy(models.Model):
    """
    A CPE that caused another CPE to be deprecated.

    One deprecation can contain one or more deprecated-by entries.

    Corresponds to: <cpe_dict_ext:deprecation-by>

    IMPORTANT:
    `name` is intentionally a string rather than a ForeignKey.

    NIST explicitly allows this value to contain a wildcard and
    therefore represent a set of products rather than an identifier
    CPE name.
    """

    NAME_CORRECTION = "NAME_CORRECTION"
    NAME_REMOVAL = "NAME_REMOVAL"
    ADDITIONAL_INFORMATION = "ADDITIONAL_INFORMATION"
    UNKNOWN = "UNKNOWN"

    DEPRECATION_TYPE_CHOICES = (
        (NAME_CORRECTION, "Name Correction"),
        (NAME_REMOVAL, "Name Removal"),
        (
            ADDITIONAL_INFORMATION,
            "Additional Information Discovery",
        ),
        (
            UNKNOWN,
            "Reason Unknown",
        ),  # DEPRECATION_TYPE missing from Official CPE Dictionary exports
    )

    deprecation = models.ForeignKey(
        CPEDeprecation,
        on_delete=models.CASCADE,
        related_name="deprecated_by",
    )

    deprecation_type = models.CharField(
        max_length=32,
        choices=DEPRECATION_TYPE_CHOICES,
    )

    name = models.CharField(
        max_length=4096,
        blank=True,
        help_text=(
            "CPE 2.3 name that deprecates this one. May contain wildcards because "
            "it could have been expanded into a product set."
        ),
    )

    class Meta:
        verbose_name = "CPE Deprecation By <cpe_dict_ext:deprecation-by>"
        verbose_name_plural = "CPE Deprecation Bys [<cpe_dict_ext:deprecation-by>]"

    def __str__(self):
        return self.name or self.deprecation_type
